# Массивы

numpy == np

pandas == pd

matplotlib == plt

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3],
               [3, 2, 1]])
print(arr)
print(arr.shape)

# одномерный массив == вектор

[[1 2 3]
 [3 2 1]]
(2, 3)


In [ ]:
arr0 = np.array([1, 2, 3])
arr1 = np.array([[1, 2, 3],
                [3, 2, 1]])
arr2 = np.array([[[1, 1, 1],
                  [2, 2, 2]],
                [[3, 3, 3],
                 [4, 4, 4]]])
print(arr0, arr1, arr2, sep="\n\n")
print(arr0.dtype, arr1.dtype, arr2.dtype)

[1 2 3]

[[1 2 3]
 [3 2 1]]

[[[1 1 1]
  [2 2 2]]

 [[3 3 3]
  [4 4 4]]]
int64 int64 int64


In [ ]:
arr_float = np.array([5, 6, 7], dtype=np.float16)
print(arr_float, arr_float.dtype, sep="\n")

[5. 6. 7.]
float16


In [ ]:
print(arr0 - arr_float)

array([-4., -4., -4.])

# Диапазоны

In [ ]:
arr0 = np.arange(5)
arr1 = np.arange(2, 14, 3, dtype=np.float16)
arr2 = np.arange(3, 5.5, 0.5)
arr3 = np.arange(8, -1, -1)
print(arr0, arr1, arr2, sep='\n')

[0 1 2 3 4]
[ 2.  5.  8. 11.]
[3.  3.5 4.  4.5 5. ]


In [ ]:
arr0 = np.linspace(3, 12, 6)
arr1 = np.linspace(2, 14, 4)
print(arr0, arr1, sep="\n")

[ 3.   4.8  6.6  8.4 10.2 12. ]
[ 2.  6. 10. 14.]


# Матрицы, чем-то связанные с математикой

In [ ]:
arr_eye = np.eye(4)
arr_eye_rect = np.eye(4, 3)
print(arr_eye, arr_eye_rect, sep='\n\n')

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [ ]:
arr = np.diag([1, 2, 3, 4])
print(arr, arr.dtype)
arr2 = np.diag([1., 2., 3.], 1)
print(arr2, arr2.dtype)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]] int64
[[0. 1. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 3.]
 [0. 0. 0. 0.]] float64


In [ ]:
arr3 = [[1, 2, 3, 4],
        [5, 6, 7, 8],
        [8, 7, 6, 5],
        [4, 3, 2, 1]]
print(np.diag(arr3), np.diag(arr3, 2), sep='\n')

[1 6 6 1]
[3 8]


In [ ]:
arr_ones = np.ones((4, 3))
arr_zeros = np.zeros((2, 3, 4), dtype=np.int_)
print(arr_ones, arr_zeros, sep='\n\n')

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [ ]:
arr_rnd = np.random.random((3, 2))
print(arr_rnd)
print()
arr_rnd_int = np.random.randint(1, 9, (2, 4))
print(arr_rnd_int)
print()
arr_sample = np.random.randn(10)
print(arr_sample)

[[0.03542208 0.96088457]
 [0.35797573 0.13395152]
 [0.30755346 0.8647963 ]]

[[4 2 2 7]
 [2 1 7 2]]

[-0.31499745  1.42185778 -0.8615932   0.98277662  0.30753378  1.11992663
  0.66697962 -0.49239291  1.33133742  1.60225713]


In [ ]:
arr_csv = np.loadtxt('arr.csv', delimiter=';', skiprows=1)
print(arr_csv)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


Def-функции:


```
def func(arg1, arg2):
    ...
    return obj
```

Lambda-функции:


```
func(..., ..., lambda x, y: <...>)
```



In [ ]:
arr_func = np.fromfunction(lambda x, y: 3 * x - 2 * y, (2, 3))
print(arr_func)
print()

def f(i, j, k):
  return i * (3 + j) + k - 1.5


arr_def = np.fromfunction(f, (2, 3, 3))
print(arr_def)

[[ 0. -2. -4.]
 [ 3.  1. -1.]]

[[[-1.5 -0.5  0.5]
  [-1.5 -0.5  0.5]
  [-1.5 -0.5  0.5]]

 [[ 1.5  2.5  3.5]
  [ 2.5  3.5  4.5]
  [ 3.5  4.5  5.5]]]


In [ ]:
arr_set = np.fromiter({11, 2, 7, 4}, dtype=float)
print(arr_set)

dic = {1: 2, 2: 4, 7: 49, 4: 16}
arr_keys = np.fromiter(dic, dtype=int)
arr_values = np.fromiter(dic.values(), dtype=int)
print(arr_keys, arr_values, sep='\n')

arr_tuple = np.fromiter((8, 6, 3, 5), dtype=int)
print(arr_tuple)

[ 2. 11.  4.  7.]
[1 2 7 4]
[ 2  4 49 16]
[8 6 3 5]


In [ ]:
import sys
import numpy as np

# data = sys.stdin.readlines()
# data = np.asmatrix(";".join(map(str.rstrip, data)))
# print(data)

temp = '1, 2, 3;4, 5, 6;7, 8, 9'
print(np.asmatrix(temp))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape, np.dtype(arr[0][0]))

(2, 3) int64


In [ ]:
arr = np.arange(18).reshape(2, 3, 3)
arr1 = np.arange(18).reshape(2, 3, -1)
print(arr1)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]


In [ ]:
arr = np.arange(6).reshape(3, 2)
print(arr)
arr.resize(2, 3)
print(arr)

[[0 1]
 [2 3]
 [4 5]]
[[0 1 2]
 [3 4 5]]


In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr[1][0], arr[0][2])

4 3


In [ ]:
arr = np.arange(1, 10)
print(arr)
print(arr[::2])
print(arr[1:8:3])
print(arr[-7:7])
print(arr[-3:3:-1])
print(arr[:-6])

[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
[2 5 8]
[3 4 5 6 7]
[7 6 5]
[1 2 3]


In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9],
                [10, 11, 12]])
print(arr[1:])
print(arr[:, 1:2])
print(arr[1:, 1:])

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 2]
 [ 5]
 [ 8]
 [11]]
[[ 5  6]
 [ 8  9]
 [11 12]]


In [ ]:
arr = np.arange(20).reshape((4, 5))
print(arr, arr[:3, 1:3], arr[:2, ::2], sep='\n')

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 1  2]
 [ 6  7]
 [11 12]]
[[0 2 4]
 [5 7 9]]


In [ ]:
arr = np.arange(30).reshape((2, 3, 5))
print(arr)
# Эквивалентно
print(arr[:, :, 1:3], arr[..., 1:3], sep='\n\n')

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
[[[ 1  2]
  [ 6  7]
  [11 12]]

 [[16 17]
  [21 22]
  [26 27]]]

[[[ 1  2]
  [ 6  7]
  [11 12]]

 [[16 17]
  [21 22]
  [26 27]]]


In [ ]:
# Эквивалентно
print(arr[1])
print(arr[1, :, :])
print(arr[1, ...])

[[15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
[[15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
[[15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [ ]:
arr = np.arange(1, 10)
print(arr[arr % 2 == 0])

[2 4 6 8]


In [ ]:
arr1 = np.arange(1, 10)
cond = arr1 % 2 != 0
print(cond)
print(arr1[cond])

[ True False  True False  True False  True False  True]
[1 3 5 7 9]


In [ ]:
arr = np.arange(20).reshape(4, 5)
print(arr)
cond = arr % 3 == 0
print(cond)
print(arr[cond])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ True False False  True False]
 [False  True False False  True]
 [False False  True False False]
 [ True False False  True False]]
[ 0  3  6  9 12 15 18]


# Арифметические операции

In [ ]:
arr = np.arange(20).reshape((4, 5))
arr1 = np.linspace(-20, 20, num=20, dtype=np.int_).reshape(4, 5)
print(arr, arr1, sep='\n\n')

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

[[-20 -18 -16 -14 -12]
 [-10  -8  -6  -4  -2]
 [  1   3   5   7   9]
 [ 11  13  15  17  20]]


In [ ]:
print(arr - arr1)
print(arr + arr1)
print(arr * arr1)
print(arr / arr1)
print(arr // arr1)
print(arr % arr1)
print(arr ** 3)

[[20 19 18 17 16]
 [15 14 13 12 11]
 [ 9  8  7  6  5]
 [ 4  3  2  1 -1]]
[[-20 -17 -14 -11  -8]
 [ -5  -2   1   4   7]
 [ 11  14  17  20  23]
 [ 26  29  32  35  39]]
[[  0 -18 -32 -42 -48]
 [-50 -48 -42 -32 -18]
 [ 10  33  60  91 126]
 [165 208 255 306 380]]
[[-0.         -0.05555556 -0.125      -0.21428571 -0.33333333]
 [-0.5        -0.75       -1.16666667 -2.         -4.5       ]
 [10.          3.66666667  2.4         1.85714286  1.55555556]
 [ 1.36363636  1.23076923  1.13333333  1.05882353  0.95      ]]
[[ 0 -1 -1 -1 -1]
 [-1 -1 -2 -2 -5]
 [10  3  2  1  1]
 [ 1  1  1  1  0]]
[[  0 -17 -14 -11  -8]
 [ -5  -2  -5   0  -1]
 [  0   2   2   6   5]
 [  4   3   2   1  19]]
[[   0    1    8   27   64]
 [ 125  216  343  512  729]
 [1000 1331 1728 2197 2744]
 [3375 4096 4913 5832 6859]]


In [ ]:
vector = np.array([2, 3, 4, 5]).reshape((4, 1))
print(vector)

print(arr * vector)

[[2]
 [3]
 [4]
 [5]]
[[ 0  2  4  6  8]
 [15 18 21 24 27]
 [40 44 48 52 56]
 [75 80 85 90 95]]


In [ ]:
arr = np.linspace(-20, 20, num=20, dtype=np.int_).reshape((4, 5))
print(arr)
arr[arr < 0] += 5
print(arr)

[[-20 -18 -16 -14 -12]
 [-10  -8  -6  -4  -2]
 [  1   3   5   7   9]
 [ 11  13  15  17  20]]
[[-15 -13 -11  -9  -7]
 [ -5  -3  -1   1   3]
 [  1   3   5   7   9]
 [ 11  13  15  17  20]]
